CREATE TABLE public.classification (
	classification_id INT GENERATED BY DEFAULT AS IDENTITY,
	classification_name CHARACTER VARYING not NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

--Data for table `classification`
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),('Sport'), ('SUV'), ('Truck'), ('Sedan');